const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getSystemInfo: () => ipcRenderer.invoke('get-system-info'),
  refreshIP: () => ipcRenderer.invoke('refresh-ip'),
  updateEnv: (ipAddress) => ipcRenderer.invoke('update-env', ipAddress),
  cleanBlockchain: () => ipcRenderer.invoke('clean-blockchain'),
  startBlockchain: () => ipcRenderer.invoke('start-blockchain'),
  startBlockchainNode1: () => ipcRenderer.invoke('start-blockchain-node1'),
  startBlockchainNode2: () => ipcRenderer.invoke('start-blockchain-node2'),
  stopBlockchainNode1: () => ipcRenderer.invoke('stop-blockchain-node1'),
  stopBlockchainNode2: () => ipcRenderer.invoke('stop-blockchain-node2'),
  stopBlockchainAll: () => ipcRenderer.invoke('stop-blockchain-all'),
  compileContract: () => ipcRenderer.invoke('compile-contract'),
  deployContract: () => ipcRenderer.invoke('deploy-contract'),
  startBackend: () => ipcRenderer.invoke('start-backend'),
  stopBackend: () => ipcRenderer.invoke('stop-backend'),
  startFrontend: (ipAddress) => ipcRenderer.invoke('start-frontend', ipAddress),
  stopFrontend: () => ipcRenderer.invoke('stop-frontend'),
  startApache: () => ipcRenderer.invoke('start-apache'),
  stopApache: () => ipcRenderer.invoke('stop-apache'),
  startMysql: () => ipcRenderer.invoke('start-mysql'),
  stopMysql: () => ipcRenderer.invoke('stop-mysql'),
  openPhpMyAdmin: () => ipcRenderer.invoke('open-phpmyadmin'),
  openXamppControl: () => ipcRenderer.invoke('open-xampp-control'),
  openBrowser: (url) => ipcRenderer.invoke('open-browser', url),
  runAllSteps: (options) => ipcRenderer.invoke('run-all-steps', options),
  onCommandOutput: (callback) => ipcRenderer.on('command-output', (event, data) => callback(data)),
  onIPChanged: (callback) => ipcRenderer.on('ip-changed', (event, data) => callback(data)),
  onIPRefreshed: (callback) => ipcRenderer.on('ip-refreshed', (event, data) => callback(data)),
  onProcessStatus: (callback) => ipcRenderer.on('process-status', (event, data) => callback(data))
});